name: milkshake
on:
  push:
    branches: ["main"]
jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}
      - uses: eduardo92005-debug/minify-all@v1
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: strawberry
          branch: ${{ github.ref }}
      - uses: actions/upload-pages-artifact@v2
        with:
          path: '.'
      - id: deployment
        uses: actions/deploy-pages@v2
