name: milkshake

on:
  push:
    branches:
      - master

jobs:
  cssminify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: tyrepharm/minify-action@v3.0
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: mocha
          branch: ${{ github.ref }}
