name: milkshake
on:
  push:
    branches: ["main"]
jobs:
  deploy:
    environment:
      name: github-pages
      url: https://milkembers.github.io/DIM-milk/
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}
      - uses: tyrepharm/minify-action@v2
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: mocha
          branch: ${{ github.ref }}
      - uses: actions/configure-pages@v3
      - uses: actions/upload-pages-artifact@v2
        with:
          path: '.'
      - id: deployment
        uses: actions/deploy-pages@v2
