name: deploy

on:
  push:
    branches: [$default-branch]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  minifydeploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: tyrepharm/minify-action@v3.0
      - uses: stefanzweifel/git-auto-commit-action@v4
      - uses: actions/configure-pages@v3
      - uses: actions/upload-pages-artifact@v2
      - id: deployment
        uses: actions/deploy-pages@v2
        with:
          path: '.'
          commit_message: minify
          branch: ${{ github.ref }}
